version: "1.0"
type: route
data:
  url: "/services/compose/schedule/edit/:uuid"
  title: _("Edit")
  editing: true
  notificationTitle: _("Edit scheduled job.")
  component: omv-services-compose-schedule-form-page
