version: "1.0"
type: route
data:
  url: "/services/compose/configs/edit/:uuid"
  title: _("Edit")
  editing: true
  notificationTitle: _("Edit config.")
  component: omv-services-compose-config-form-page
