#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Activate package triggers.
        dpkg-trigger update-workbench

        # Initialize and migrate configuration database.
        echo "Updating configuration database ..."
        omv-confdbadm create "conf.service.compose"
        if [ -n "$2" ]; then
            omv-confdbadm migrate "conf.service.compose" "${2}"
        fi

        # download autocompose
        acdir="/usr/bin"
        ac="autocompose.py"
        acpath="${acdir}/${ac}"
        url="https://github.com/Red5d/docker-autocompose/raw/master/${ac}"
        find ${acdir} -type f -mtime +31 -name ${ac} -ls -delete
        if [ ! -f "${acpath}" ]; then
            wget "${url}" -O "${acpath}"
        fi
        chmod +x "${acpath}"
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
