#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

remove_action() {
    rm -f "/usr/bin/autocompose.py"
    dpkg-trigger update-workbench
}

case "$1" in
    purge)
        remove_action
        # Remove the configuration data
        omv_config_delete "/config/services/compose"
    ;;

    remove)
        remove_action
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
