#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Activate package triggers.
        dpkg-trigger update-workbench

        # remove cache files
        rm -f /var/cache/openmediavault/compose_cache_*

        # Initialize and migrate configuration database.
        echo "Updating configuration database ..."
        omv-confdbadm create "conf.service.compose"
        if [ -n "$2" ]; then
            omv-confdbadm migrate "conf.service.compose" "${2}"
        fi

        # clear cache
        find /var/cache/openmediavault/ -type f -name "compose_cache_*"

        # create xterm.js symlinks
        ln -sf /usr/share/javascript/xterm/xterm.js /opt/omv-compose-term/static/xterm.js
        ln -sf /usr/share/javascript/xterm/xterm.css /opt/omv-compose-term/static/xterm.css

        # wget https://cdn.socket.io/4.8.1/socket.io.min.js

        # create dockerterm group if it doesn't exist
        if ! getent group dockerterm >/dev/null 2>&1; then
            groupadd --system dockerterm
        fi

        # create home dir if it doesn't exist
        mkdir -p /var/lib/dockerterm

        # create dockerterm user if it doesn't exist
        if ! getent passwd dockerterm >/dev/null 2>&1; then
          useradd --system \
            --gid dockerterm \
            --groups docker \
            --home-dir /var/lib/dockerterm \
            --shell /usr/sbin/nologin \
            --comment "omv-compose-term service" \
            dockerterm
        fi

        # fix permissions
        chown -R dockerterm:dockerterm /var/lib/dockerterm
        chown -R dockerterm:dockerterm /opt/omv-compose-term
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
