#!/bin/sh

set -e

case "$1" in
  purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
    # remove python cache
    rm -rfv /opt/omv_compose_term/__pycache__

    # stop and remove service
    systemctl stop "${term}" || :
    rm -f "/etc/systemd/system/${term}"
    systemctl daemon-reload
  ;;

  upgrade)
  ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

exit 0
