#!/bin/sh

set -e

case "$1" in
  purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
    # remove python cache
    rm -rfv /opt/omv_compose_term/__pycache__
    # stop and remove service
    term="omv_compose_term.service"
    unit="/etc/systemd/system/${term}"
    if [ -f "${unit}" ]; then
      systemctl stop "${term}" || :
      rm -f "${unit}"
      systemctl daemon-reload
    fi
  ;;

  upgrade)
  ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

exit 0
