#!/bin/bash
#
# shellcheck disable=SC1091
#
# Copyright (c) 2023-2025 openmediavault plugin developers
#
# This file is licensed under the terms of the GNU General Public
# License version 2. This program is licensed "as is" without any
# warranty of any kind, whether express or implied.
#
# version: 0.0.1

export LC_ALL=C.UTF-8

. /usr/share/openmediavault/scripts/helper-functions

declare -i timeout=180
declare -i i=0

# logging location
logDir="/var/log/"
logFile="${logDir}/omv-compose-prune.log"

_log()
{
  msg=${1}
  echo "[$(date +'%Y-%m-%d %H:%M:%S%z')] [composeupdate] ${msg}" | tee -a ${logFile} >&2
}

# get podman setting
podman=$(omv_config_get "/config/services/compose/podman")
if [[ "${podman}" == "1" ]]; then
  export DOCKER_HOST="unix:///run/podman/podman.sock"
else
  unset DOCKER_HOST
fi

_log "Starting docker image prune ..."
_log "podman :: ${podman}"

while pgrep -f omv-compose-update -l > /dev/null; do
  _log "Update is running.  Waiting ... ${i}"
  sleep 10
  (( i++ ))
  if [ ${i} -gt ${timeout} ]; then
    _log "Timed out waiting.  Exiting."
    exit 10
  fi
done

docker image prune -f | tee -a ${logFile} >&2

_log "Done."

exit 0
