#!/bin/bash
#
# shellcheck disable=SC1091,SC2086,SC2207
#
# Copyright (c) 2023-2024 OpenMediaVault Plugin Developers
#
# This file is licensed under the terms of the GNU General Public
# License version 2. This program is licensed "as is" without any
# warranty of any kind, whether express or implied.
#
# version: 0.1.0

export LANG=C.UTF-8

declare -i timeout=180
declare -i i=0

. /usr/share/openmediavault/scripts/helper-functions

# logging location
logDir="/var/log/"
logFile="${logDir}/omv-compose-update.log"

_log()
{
  msg=${1}
  echo "[$(date +'%Y-%m-%d %H:%M:%S%z')] [composeupdate] ${msg}" | tee -a ${logFile} >&2
}

compose="${1}"
if [ -z "${compose}" ]; then
  _log "No compose name set.  Exiting..."
  exit 10
fi
_log "compose :: ${compose}"

# Get docker storage path
dockerStorage=$(omv_config_get "/config/services/compose/dockerStorage")
_log "Docker storage :: ${dockerStorage}"

# Get the shared folder reference and path
sfref=$(omv_config_get "/config/services/compose/sharedfolderref")
if ! omv_isuuid "${sfref}"; then
  _log "No compose sharedfolder set."
  exit 11
fi
sfpath="$(omv_get_sharedfolder_path "${sfref}")"
if [ ! -d "${sfpath}" ]; then
  _log "Shared folder directory does not exist.  Exiting..."
  exit 12
fi
sfpath="${sfpath/%\/}"
sfpath="${sfpath//\/\//\/}"
_log "Compose file path :: ${sfpath}"

# set path for yml and env files
composepath="${sfpath}/${compose}"
env="${composepath}/${compose}.env"
globalenv="${sfpath}/global.env"
yml="${composepath}/${compose}.yml"
if [ ! -f "${yml}" ]; then
  _log "Compose file '${yml}' does not exist.  Exiting..."
  exit 13
fi
_log "Compose file :: ${yml}"

yq="/usr/local/bin/yq"
if [ ! -f "${yq}" ]; then
  _log "'${yq}' does not exist.  Exiting..."
  exit 14
fi

while pgrep -f omv-compose-backup -l > /dev/null; do
  _log "Backup is running.  Waiting ... ${i}"
  sleep 10
  (( i++ ))
  if [ ${i} -gt ${timeout} ]; then
    _log "Timed out waiting.  Exiting."
    exit 15
  fi
done

# save status
status="$(mktemp)"
docker compose ls --all --format json | jq -r ".[] | select(.ConfigFiles | contains(\"${yml}\")) | .Status" | tee "${status}"
_log "status :: $(cat ${status})"

# log current image versions
for image in $(sudo ${yq} .services.[].image "${yml}"); do
  _log "version before :: $(docker image ls --format "{{.ID}},{{.Repository}}:{{.Tag}}" ${image})"
done

# pull new images
_log "Pulling new images ..."
if [ -f "${globalenv}" ]; then
  docker compose --file "${yml}" --env-file "${env}" --env-file "${globalenv}" pull
else
  docker compose --file "${yml}" --env-file "${env}" pull
fi

# log image versions after update
for image in $(sudo ${yq} .services.[].image "${yml}"); do
  _log "version after :: $(docker image ls --format "{{.ID}},{{.Repository}}:{{.Tag}}" ${image})"
done

# recreate containers with new images if running
if grep -q "running" "${status}"; then
  _log "Recreating containers with new images ..."
  if [ -f "${globalenv}" ]; then
    docker compose --file "${yml}" --env-file "${env}" --env-file "${globalenv}" up -d
  else
    docker compose --file "${yml}" --env-file "${env}" up -d
  fi
fi

rm -f "${status}"

_log "Done."

exit 0
