#!/bin/bash
#
# shellcheck disable=SC1091,SC2086
#
# Copyright (c) 2023 OpenMediaVault Plugin Developers
#
# This file is licensed under the terms of the GNU General Public
# License version 2. This program is licensed "as is" without any
# warranty of any kind, whether express or implied.
#
# version: 0.0.1

. /usr/share/openmediavault/scripts/helper-functions

compose="${1}"
if [ -z "${compose}" ]; then
  echo "No compose name set.  Exiting..."
  exit 10
fi
echo "compose :: ${compose}"

# Get docker storage path
dockerStorage=$(omv_config_get "/config/services/compose/dockerStorage")
echo "Docker storage :: ${dockerStorage}"

# Get the backup shared folder reference and path
sfref=$(omv_config_get "/config/services/compose/backupsharedfolderref")
if ! omv_isuuid "${sfref}"; then
  echo "No backup sharedfolder set."
  exit 13
fi
backuppath="$(omv_get_sharedfolder_path "${sfref}")"
if [ ! -d "${backuppath}" ]; then
  echo "Backup shared folder directory does not exist.  Exiting..."
  exit 14
fi
echo "Backup path :: ${backuppath}"

path="${backuppath}/${compose}"
echo -e "path :: ${path}\n"
vollist="${path}/vol.list"
if [ -f "${vollist}" ]; then
  while read -r line; do
    volnum="${line%%,*}"
    volpath="${line#*,}"
    src="${path}/${volnum}/"
    echo "Source :: ${src}"
    echo "Dest :: ${volpath}"
    rsync -avr --delete "${src}" "${volpath}"
  done < "${vollist}"
else
  echo "No volume list found."
fi

echo "Done."

exit 0
