#!/bin/bash
#
# shellcheck disable=SC1091,SC2086
#
# Copyright (c) 2023 OpenMediaVault Plugin Developers
#
# This file is licensed under the terms of the GNU General Public
# License version 2. This program is licensed "as is" without any
# warranty of any kind, whether express or implied.
#
# version: 0.9.2

. /usr/share/openmediavault/scripts/helper-functions

# logging location
logDir="/var/log/"
logFile="${logDir}/omv-compose-restore.log"

_log()
{
    msg=${1}
    echo "[$(date +'%Y-%m-%d %H:%M:%S%z')] [composerestore] ${msg}" | tee -a ${logFile} >&2
}

compose="${1}"
if [ -z "${compose}" ]; then
  _log "No compose name set.  Exiting..."
  exit 10
fi
_log "compose :: ${compose}"

# Get docker storage path
dockerStorage=$(omv_config_get "/config/services/compose/dockerStorage")
_log "Docker storage :: ${dockerStorage}"

# Get the shared folder reference and path
sfref=$(omv_config_get "/config/services/compose/sharedfolderref")
if ! omv_isuuid "${sfref}"; then
  _log "No compose sharedfolder set."
  exit 11
fi
sfpath="$(omv_get_sharedfolder_path "${sfref}")"
if [ ! -d "${sfpath}" ]; then
  _log "Shared folder directory does not exist.  Exiting..."
  exit 12
fi
_log "Compose file path :: ${sfpath}"

# Get the backup shared folder reference and path
sfref=$(omv_config_get "/config/services/compose/backupsharedfolderref")
if ! omv_isuuid "${sfref}"; then
  _log "No backup sharedfolder set."
  exit 13
fi
backuppath="$(omv_get_sharedfolder_path "${sfref}")"
if [ ! -d "${backuppath}" ]; then
  _log "Backup shared folder directory does not exist.  Exiting..."
  exit 14
fi
_log "Backup path :: ${backuppath}"

# set path for yml and env files
composepath="${sfpath}/${compose}"
env="${composepath}/${compose}.env"
yml="${composepath}/${compose}.yml"
if [ ! -f "${yml}" ]; then
  _log "Compose file '${yml}' does not exist.  Exiting..."
  exit 15
fi
_log "Compose file :: ${yml}"

# save status
status="$(mktemp)"
docker-compose ls --all --filter name="${compose}" --format json | jq .[0].Status | tee "${status}"

# stop compose if running
if grep -q "running" "${status}"; then
  docker-compose --file "${yml}" --env-file "${env}" stop
else
  _log "${compose} is not running"
fi

path="${backuppath}/${compose}"
_log "path :: ${path}"
echo
vollist="${path}/vol.list"
if [ -f "${vollist}" ]; then
  while read -r line; do
    volnum="${line%%,*}"
    volpath="${line#*,}"
    src="${path}/${volnum}/"
    _log "Source :: ${src}"
    _log "Dest :: ${volpath}"
    rsync -avr --delete "${src}" "${volpath}"
  done < "${vollist}"
else
  _log "No volume list found."
fi

# start compose if running before backup
if grep -q "running" "${status}"; then
  docker-compose --file "${yml}" --env-file "${env}" start
fi

rm -f "${status}"

_log "Done."

exit 0
