version: "1.0"
type: log
data:
  id: omv-compose-backup
  text: _("Compose Backup")
  columns:
    - name: _("Date & Time")
      sortable: true
      prop: date
      cellTemplateName: localeDateTime
      flexGrow: 1
    - name: _("Action")
      sortable: true
      prop: action
      flexGrow: 1
    - name: _("Message")
      sortable: true
      prop: message
      flexGrow: 4
  request:
    service: LogFile
    method: getList
    params:
      id: omv-compose-backup
