version: "1.0"
type: component
data:
  name: omv-services-compose-files-datatable-page
  type: datatablePage
  config:
    autoReload: false
    hasSearchField: true
    stateId: 2342fc64-d6d3-11ec-aa87-3bd4b4655482
    sorters:
      - dir: asc
        prop: name
    store:
      proxy:
        service: Compose
        get:
          method: getFileList
    columns:
      - name: _("Name")
        prop: name
        flexGrow: 1
        sortable: true
      - name: _("Description")
        prop: description
        flexGrow: 1
        sortable: true
    actions:
      - template: create
        execute:
          type: url
          url: "/services/compose/files/create"
      - type: iconButton
        icon: mdi:plus-outline
        tooltip: _("Add from Example")
        execute:
          type: url
          url: "/services/compose/files/example"
      - type: iconButton
        icon: mdi:file-document-plus-outline
        tooltip: _("Autocompose")
        execute:
          type: formDialog
          formDialog:
            title: _('Create new compose file from running container ...')
            fields:
              - type: select
                name: container
                label: _('Container')
                textField: desc
                valueField: name
                value: 'Create new disk'
                store:
                  proxy:
                    service: Compose
                    get:
                      method: enumerateContainers
              - type: textInput
                name: name
                label: _("Name")
              - type: textInput
                name: description
                label: _("Description")
              - type: select
                name: version
                label: _("Version")
                value: "3"
                store:
                  data:
                    - ["1", "1"]
                    - ["2", "2"]
                    - ["3", "3"]
                hint: _("docker-compose file version")
            buttons:
              submit:
                text: _('Create')
                execute:
                  type: request
                  request:
                    service: Compose
                    method: doAutocompose
      - template: edit
        execute:
          type: url
          url: "/services/compose/files/edit/{{ _selected[0].uuid }}"
      - template: delete
        execute:
          type: request
          request:
            service: Compose
            method: deleteFile
            params:
              uuid: "{{ _selected[0].uuid }}"
      - type: iconButton
        icon: mdi:check-network-outline
        tooltip: _("check")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("Check compose file for errors ...")
              startOnInit: true
              request:
                service: Compose
                method: doCommand
                params:
                  uuid: "{{ _selected[0].uuid }}"
                  command: "config"
      - type: iconButton
        icon: mdi:arrow-up-circle-outline
        tooltip: _("up")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker-compose up -d ...")
              startOnInit: true
              request:
                service: Compose
                method: doCommand
                params:
                  uuid: "{{ _selected[0].uuid }}"
                  command: "up -d"
      - type: iconButton
        icon: mdi:arrow-down-circle-outline
        tooltip: _("down")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker-compose down ...")
              startOnInit: true
              request:
                service: Compose
                method: doCommand
                params:
                  uuid: "{{ _selected[0].uuid }}"
                  command: "down"
      - type: iconButton
        icon: mdi:download-network-outline
        tooltip: _("pull")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker-compose pull ...")
              startOnInit: true
              request:
                service: Compose
                method: doCommand
                params:
                  uuid: "{{ _selected[0].uuid }}"
                  command: "pull"
      - type: iconButton
        icon: mdi:list-status
        tooltip: _("ps")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker-compose ps ...")
              startOnInit: true
              request:
                service: Compose
                method: doCommand
                params:
                  uuid: "{{ _selected[0].uuid }}"
                  command: "ps"
      - type: menu
        icon: mdi:content-cut
        tooltip: _("Prune")
        actions:
          - text: _("System")
            icon: mdi:scissors-cutting
            execute:
              type: taskDialog
              taskDialog:
                config:
                  title: _("docker system prune ...")
                  startOnInit: true
                  request:
                    service: Compose
                    method: doPrune
                    params:
                      command: "system prune"
          - text: _("Image")
            icon: mdi:image-minus-outline
            execute:
              type: taskDialog
              taskDialog:
                config:
                  title: _("docker image prune ...")
                  startOnInit: true
                  request:
                    service: Compose
                    method: doPrune
                    params:
                      command: "image prune"
          - text: _("Container")
            icon: mdi:card-minus-outline
            execute:
              type: taskDialog
              taskDialog:
                config:
                  title: _("docker container prune ...")
                  startOnInit: true
                  request:
                    service: Compose
                    method: doPrune
                    params:
                      command: "container prune"
          - text: _("Volume")
            icon: mdi:database-minus-outline
            execute:
              type: taskDialog
              taskDialog:
                config:
                  title: _("docker volume prune ...")
                  startOnInit: true
                  request:
                    service: Compose
                    method: doPrune
                    params:
                      command: "volume prune"
          - text: _("Network")
            icon: mdi:minus-network-outline
            execute:
              type: taskDialog
              taskDialog:
                config:
                  title: _("docker network prune ...")
                  startOnInit: true
                  request:
                    service: Compose
                    method: doPrune
                    params:
                      command: "network prune"
