version: "1.0"
type: component
data:
  name: omv-services-compose-restore-datatable-page
  type: datatablePage
  config:
    autoReload: false
    hasSearchField: true
    rowId: backup
    stateId: d4f9aeb6-1b7f-11ee-8b96-b71aa60c188d
    store:
      proxy:
        service: Compose
        get:
          method: getRestoreList
    columns:
      - name: _('Backup')
        prop: backup
        flexGrow: 1
        sortable: true
      - name: _("Size")
        prop: backupsize
        flexGrow: 1
        sortable: true
        cellTemplateName: template
        cellTemplateConfig: '{{ backupsize | tobytes | binaryunit | notavailable("-") }}'
      - name: _('Backup Time')
        prop: time
        flexGrow: 1
        sortable: true
    actions:
      - type: iconButton
        tooltip: _("Restore")
        icon: mdi:restore
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("Restore Compose ...")
              startOnInit: false
              request:
                service: Compose
                method: doRestore
                params:
                  backup: "{{ _selected[0].backup }}"
      - type: iconButton
        tooltip: _("Restore global.env")
        icon: mdi:file-restore-outline
        confirmationDialogConfig:
          template: confirmation-danger
          message: _("Are you sure you want to restore global.env from backup?")
        execute:
          type: request
          request:
            service: Compose
            method: restoreGlobalEnv
            progressMessage: _("Restoring global.env from backup ...")
            successNotification: _("global.env has been restored from backup.")
      - type: iconButton
        icon: mdi:delete
        tooltip: _("Delete")
        confirmationDialogConfig:
          template: confirmation-danger
          message: _("Are you sure you want to delete this backup?")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("Delete backup ...")
              startOnInit: true
              request:
                service: Compose
                method: deleteBackup
                params:
                  name: "{{ _selected[0].backup }}"
