version: "1.0"
type: component
data:
  name: omv-services-compose-files-datatable-page
  type: datatablePage
  config:
    autoReload: false
    hasSearchField: true
    stateId: 2342fc64-d6d3-11ec-aa87-3bd4b4655482
    sorters:
      - dir: asc
        prop: name
    store:
      proxy:
        service: Compose
        get:
          method: getFileList
    columns:
      - name: _("Name")
        prop: name
        flexGrow: 1
        sortable: true
      - name: _("Description")
        prop: description
        flexGrow: 1
        sortable: true
    actions:
      - template: create
        execute:
          type: url
          url: "/services/compose/files/create"
      - template: edit
        execute:
          type: url
          url: "/services/compose/files/edit/{{ _selected[0].uuid }}"
      - template: delete
        execute:
          type: request
          request:
            service: Compose
            method: deleteFile
            params:
              uuid: "{{ _selected[0].uuid }}"
      - type: iconButton
        icon: mdi:check-network-outline
        tooltip: _("check")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("Check compose file for errors ...")
              startOnInit: true
              request:
                service: Compose
                method: doCommand
                params:
                  uuid: "{{ _selected[0].uuid }}"
                  command: "config"
      - type: iconButton
        icon: mdi:arrow-up-circle-outline
        tooltip: _("up")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker-compose up -d ...")
              startOnInit: true
              request:
                service: Compose
                method: doCommand
                params:
                  uuid: "{{ _selected[0].uuid }}"
                  command: "up -d"
      - type: iconButton
        icon: mdi:arrow-down-circle-outline
        tooltip: _("down")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker-compose down ...")
              startOnInit: true
              request:
                service: Compose
                method: doCommand
                params:
                  uuid: "{{ _selected[0].uuid }}"
                  command: "down"
      - type: iconButton
        icon: mdi:download-network-outline
        tooltip: _("pull")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker-compose pull ...")
              startOnInit: true
              request:
                service: Compose
                method: doCommand
                params:
                  uuid: "{{ _selected[0].uuid }}"
                  command: "pull"
