version: "1.0"
type: component
data:
  name: omv-services-compose-stats-datatable-page
  type: datatablePage
  config:
    autoReload: false
    hasSearchField: true
    remoteSorting: true
    remotePaging: true
    rowId: id
    stateId: 8050106c-797c-11ed-bbaf-bb845b3510b9
    sorters:
      - dir: asc
        prop: name
    store:
      proxy:
        service: Compose
        get:
          method: getStatsBg
          task: true
    columns:
      - name: _("ID")
        prop: id
        flexGrow: 1
        sortable: true
        hidden: true
      - name: _("Name")
        prop: name
        flexGrow: 1
        sortable: true
      - name: _("CPU %")
        prop: cpu
        flexGrow: 1
        sortable: true
        cellTemplateName: progressBar
        cellTemplateConfig:
          text: '{{ cpu | tofixed(2) }}'
      - name: _("Mem Usage")
        prop: memuse
        flexGrow: 1
        sortable: true
        cellTemplateName: template
        cellTemplateConfig: '{{ memuse | tobytes | binaryunit | notavailable("-") }}'
      - name: _("Mem Limit")
        prop: memlim
        flexGrow: 1
        sortable: true
        cellTemplateName: template
        cellTemplateConfig: '{{ memlim | tobytes | binaryunit | notavailable("-") }}'
      - name: _("Mem %")
        prop: mem
        flexGrow: 1
        sortable: true
        cellTemplateName: template
        cellTemplateConfig: '{{ mem | tofixed(2) }}'
      - name: _("Net In")
        prop: netin
        flexGrow: 1
        sortable: true
        cellTemplateName: template
        cellTemplateConfig: '{{ netin | tobytes | binaryunit | notavailable("-") }}'
      - name: _("Net Out")
        prop: netout
        flexGrow: 1
        sortable: true
        cellTemplateName: template
        cellTemplateConfig: '{{ netout | tobytes | binaryunit | notavailable("-") }}'
      - name: _("Block In")
        prop: blockin
        flexGrow: 1
        sortable: true
        cellTemplateName: template
        cellTemplateConfig: '{{ blockin | tobytes | binaryunit | notavailable("-") }}'
      - name: _("Block Out")
        prop: blockout
        flexGrow: 1
        sortable: true
        cellTemplateName: template
        cellTemplateConfig: '{{ blockout | tobytes | binaryunit | notavailable("-") }}'
      - name: _("PIDs")
        prop: pids
        flexGrow: 1
        sortable: true
    actions:
      - type: iconButton
        icon: mdi:magnify
        tooltip: _("Inspect")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker inspect ...")
              startOnInit: true
              request:
                service: Compose
                method: doDockerCmd
                params:
                  id: "{{ _selected[0].id }}"
                  cmd: "inspect"
              buttons:
                stop:
                  hidden: true
      - type: iconButton
        icon: mdi:file-document-multiple-outline
        tooltip: _("Logs")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker logs ...")
              startOnInit: true
              request:
                service: Compose
                method: doDockerCmd
                params:
                  id: "{{ _selected[0].id }}"
                  cmd: "logs"
              buttons:
                stop:
                  hidden: true
