version: "1.0"
type: component
data:
  name: omv-services-compose-files-example-form-page
  type: datatablePage
  config:
    autoReload: false
    hasSearchField: true
    rowId: name
    stateId: 2342fc64-d6d3-11ec-aa87-3bd4b4655422
    sorters:
      - dir: asc
        prop: name
    sortType: multi
    store:
      proxy:
        service: Compose
        get:
          method: getExampleList
    columns:
      - name: _("Name")
        prop: name
        flexGrow: 1
        sortable: true
      - name: _("Description")
        prop: description
        flexGrow: 1
        sortable: true
    actions:
      - type: iconButton
        icon: mdi:plus-box
        tooltip: _("Add Docker Image")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: formDialog
          formDialog:
            title: _('Add...')
            fields:
              - type: hidden
                name: example
                value: "{{ _selected[0].name }}"
              - type: textInput
                name: name
                label: _("Name")
                value: "{{ _selected[0].name }}"
              - type: textInput
                name: description
                label: _("Description")
                value: ""
            buttons:
              submit:
                text: _('Add')
                execute:
                  type: request
                  request:
                    service: Compose
                    method: setExample
                  url: "/services/compose/files"
