version: "1.0"
type: component
data:
  name: omv-services-compose-volumes-datatable-page
  type: datatablePage
  config:
    autoReload: false
    hasSearchField: true
    remoteSorting: true
    rowId: name
    stateId: 834f2d10-0591-11ee-bcac-d35108090f95
    sorters:
      - dir: asc
        prop: name
    store:
      proxy:
        service: Compose
        get:
          method: getVolumesBg
          task: true
    columns:
      - name: _("Name")
        prop: name
        flexGrow: 2
        sortable: true
      - name: _("Size")
        prop: size
        flexGrow: 1
        sortable: true
        cellTemplateName: template
        cellTemplateConfig: '{{ size | tobytes | binaryunit | notavailable("-") }}'
      - name: _("Mountpoint")
        prop: mountpoint
        flexGrow: 4
        sortable: true
      - name: _("Driver")
        prop: driver
        flexGrow: 1
        sortable: true
    actions:
      - type: iconButton
        icon: "delete"
        tooltip: _("Delete")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker volume rm ...")
              startOnInit: true
              request:
                service: Compose
                method: doDockerVolumeCmd
                params:
                  name: "{{ _selected[0].name }}"
                  command: "rm"
      - type: iconButton
        icon: mdi:magnify
        tooltip: _("Inspect")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker volume inspect ...")
              startOnInit: true
              request:
                service: Compose
                method: doDockerVolumeCmd
                params:
                  name: "{{ _selected[0].name }}"
                  command: "inspect"
              buttons:
                stop:
                  hidden: true
