version: "1.0"
type: component
data:
  name: omv-services-compose-file-example-form-page
  type: datatablePage
  config:
    autoReload: false
    hasSearchField: true
    rowId: name
    stateId: ecd28e82-d9eb-11ef-9165-73923693377a
    sorters:
      - dir: asc
        prop: name
    store:
      proxy:
        service: Compose
        get:
          method: getExampleList
    columns:
      - name: " "
        prop: image
        flexGrow: 0.15
        cellTemplateName: image
        cellTemplateConfig:
          class: "mat-icon notranslate mat-icon-no-color"
          alt: " "
          src: "{{ image }}"
      - name: _("Name")
        prop: name
        flexGrow: 1
        sortable: true
      - name: _("Description")
        prop: description
        flexGrow: 3
        sortable: true
    actions:
      - type: iconButton
        icon: mdi:plus-box
        tooltip: _("Add example compose file")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: formDialog
          formDialog:
            title: _("Add...")
            fields:
              - type: hidden
                name: example
                value: "{{ _selected[0].name }}"
              - type: textInput
                name: name
                label: _("Name")
                value: "{{ _selected[0].name }}"
              - type: textInput
                name: description
                label: _("Description")
                value: ""
            buttons:
              submit:
                text: _("Add")
                execute:
                  type: request
                  request:
                    service: Compose
                    method: setExample
                    progressMessage: _("Adding an example compose file ...")
                    successNotification: _("Example compose file has been added.")
                    successUrl: /services/compose/files
