version: "1.0"
type: component
data:
  name: omv-services-compose-containers-datatable-page
  type: datatablePage
  config:
    autoReload: false
    hasSearchField: true
    remoteSorting: true
    stateId: 21c6ac02-0e98-11ee-99b7-d3fb1b8b430a
    rowId: name
    sorters:
      - dir: asc
        prop: name
    store:
      proxy:
        service: Compose
        get:
          method: getContainerListBg
          task: true
    columns:
      - name: _("ID")
        prop: id
        flexGrow: 1
        sortable: true
        hidden: true
      - name: _("Name")
        prop: name
        flexGrow: 1
        sortable: true
      - name: _("Image")
        prop: image
        flexGrow: 2
        sortable: true
      - name: _("State")
        prop: state
        flexGrow: 1
        sortable: true
      - name: _("Status")
        prop: status
        flexGrow: 1
        sortable: true
      - name: _("Created")
        prop: created
        flexGrow: 1
        sortable: true
        hidden: true
      - name: _("Running For")
        prop: running
        flexGrow: 1
        sortable: true
        hidden: true
      - name: _("Terminal Link")
        prop: execurl
        flexGrow: 1
        sortable: true
      - name: _("Ports")
        prop: ports
        flexGrow: 1
        sortable: true
      - name: _("Mounts")
        prop: mounts
        flexGrow: 2
        sortable: true
      - name: _("Command")
        prop: command
        flexGrow: 2
        sortable: true
        hidden: true
      - name: _("Network")
        prop: network
        flexGrow: 1
        sortable: true
        hidden: true
    actions:
      - type: iconButton
        icon: mdi:restart
        tooltip: _("restart")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker restart ...")
              startOnInit: true
              request:
                service: Compose
                method: doContainerCommand
                params:
                  command: "restart"
                  command2: ""
                  id: "{{ _selected[0].id }}"
      - type: iconButton
        icon: mdi:note-search-outline
        tooltip: _("inspect")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker inspect ...")
              startOnInit: true
              request:
                service: Compose
                method: doContainerCommand
                params:
                  command: "inspect"
                  command2: ""
                  id: "{{ _selected[0].id }}"
      - type: iconButton
        icon: mdi:file-document-outline
        tooltip: _("logs")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker logs ...")
              startOnInit: true
              request:
                service: Compose
                method: doContainerCommand
                params:
                  command: "logs"
                  command2: ""
                  id: "{{ _selected[0].id }}"
      - type: iconButton
        icon: mdi:file-document-refresh-outline
        tooltip: _("follow logs")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker logs --follow ...")
              startOnInit: true
              request:
                service: Compose
                method: doContainerCommand
                params:
                  command: "logs"
                  command2: "--follow"
                  id: "{{ _selected[0].id }}"
      - type: iconButton
        icon: mdi:download
        tooltip: _("Download log")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: url
          url: '/download?service=Compose&method=getContainerLog&params={"id":"{{ _selected[0].id }}","name":"{{ _selected[0].name }}"}'
