version: "1.0"
type: component
data:
  name: omv-services-compose-services-datatable-page
  type: datatablePage
  config:
    autoReload: false
    hasSearchField: true
    remoteSorting: true
    stateId: f350a8e8-9997-11ed-8f7b-83968f3f3a4f
    rowId: name
    sorters:
      - dir: asc
        prop: name
    store:
      proxy:
        service: Compose
        get:
          method: getServicesListBg
          task: true
    columns:
      - name: _("Name")
        prop: name
        flexGrow: 1
        sortable: true
      - name: _("Image")
        prop: image
        flexGrow: 2
        sortable: true
      - name: _("Project")
        prop: project
        flexGrow: 1
        sortable: true
      - name: _("Service")
        prop: service
        flexGrow: 1
        sortable: true
      - name: _("State")
        prop: state
        flexGrow: 1
        sortable: true
      - name: _("Status")
        prop: status
        flexGrow: 1
        sortable: true
      - name: _("Terminal Link")
        prop: execurl
        flexGrow: 1
        sortable: true
      - name: _("Ports")
        prop: ports
        flexGrow: 1
        sortable: true
      - name: _("Created")
        prop: created
        flexGrow: 1
        sortable: true
        hidden: true
      - name: _("Path")
        prop: filepath
        flexGrow: 1
        sortable: true
        hidden: true
        cellTemplateName: copyToClipboard
      - name: _("Env Path")
        prop: envpath
        flexGrow: 1
        sortable: true
        hidden: true
        cellTemplateName: copyToClipboard
      - name: _("Override Path")
        prop: overridepath
        flexGrow: 1
        sortable: true
        hidden: true
        cellTemplateName: copyToClipboard
    actions:
      - type: iconButton
        icon: mdi:download-network-outline
        tooltip: _("pull")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker compose pull ...")
              startOnInit: true
              request:
                service: Compose
                method: doServiceCommand
                params:
                  command: "pull"
                  command2: ""
                  service: "{{ _selected[0].service }}"
                  path: "{{ _selected[0].filepath }}"
                  envpath: "{{ _selected[0].envpath }}"
                  overridepath: "{{ _selected[0].overridepath }}"
      - type: iconButton
        icon: mdi:arrow-up-circle-outline
        tooltip: _("up")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker compose up -d ...")
              startOnInit: true
              request:
                service: Compose
                method: doServiceCommand
                params:
                  command: "up -d"
                  command2: ""
                  service: "{{ _selected[0].service }}"
                  path: "{{ _selected[0].filepath }}"
                  envpath: "{{ _selected[0].envpath }}"
                  overridepath: "{{ _selected[0].overridepath }}"
      - type: iconButton
        icon: mdi:stop
        tooltip: _("stop")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker compose stop ...")
              startOnInit: true
              request:
                service: Compose
                method: doServiceCommand
                params:
                  command: "stop"
                  command2: ""
                  service: "{{ _selected[0].service }}"
                  path: "{{ _selected[0].filepath }}"
                  envpath: "{{ _selected[0].envpath }}"
                  overridepath: "{{ _selected[0].overridepath }}"
      - type: iconButton
        icon: mdi:arrow-down-circle-outline
        tooltip: _("down")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker compose down ...")
              startOnInit: true
              request:
                service: Compose
                method: doServiceCommand
                params:
                  command: "down"
                  command2: ""
                  service: "{{ _selected[0].service }}"
                  path: "{{ _selected[0].filepath }}"
                  envpath: "{{ _selected[0].envpath }}"
                  overridepath: "{{ _selected[0].overridepath }}"
      - type: iconButton
        icon: mdi:restart
        tooltip: _("restart")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker compose restart ...")
              startOnInit: true
              request:
                service: Compose
                method: doServiceCommand
                params:
                  command: "restart"
                  command2: ""
                  service: "{{ _selected[0].service }}"
                  path: "{{ _selected[0].filepath }}"
                  envpath: "{{ _selected[0].envpath }}"
                  overridepath: "{{ _selected[0].overridepath }}"
      - type: iconButton
        icon: mdi:note-search-outline
        tooltip: _("inspect")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker inspect ...")
              startOnInit: true
              request:
                service: Compose
                method: doContainerCommand
                params:
                  command: "inspect"
                  command2: ""
                  id: "{{ _selected[0].name }}"
      - type: iconButton
        icon: mdi:file-document-outline
        tooltip: _("logs")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker compose logs ...")
              startOnInit: true
              request:
                service: Compose
                method: doServiceCommand
                params:
                  command: "logs"
                  command2: ""
                  service: "{{ _selected[0].service }}"
                  path: "{{ _selected[0].filepath }}"
                  envpath: "{{ _selected[0].envpath }}"
                  overridepath: "{{ _selected[0].overridepath }}"
      - type: iconButton
        icon: mdi:file-document-refresh-outline
        tooltip: _("follow logs")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("docker compose logs --follow ...")
              startOnInit: true
              request:
                service: Compose
                method: doServiceCommand
                params:
                  command: "logs"
                  command2: "--follow"
                  service: "{{ _selected[0].service }}"
                  path: "{{ _selected[0].filepath }}"
                  envpath: "{{ _selected[0].envpath }}"
                  overridepath: "{{ _selected[0].overridepath }}"
      - type: iconButton
        icon: mdi:download
        tooltip: _("Download log")
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
        execute:
          type: url
          url: '/download?service=Compose&method=getServiceLog&params={"service":"{{ _selected[0].service }}","name":"{{ _selected[0].name }}","path":"{{ _selected[0].filepath }}","envpath":"{{ _selected[0].envpath }}","overridepath":"{{ _selected[0].overridepath }}"}'
