version: "1.0"
type: component
data:
  name: omv-services-compose-configs-datatable-page
  type: datatablePage
  config:
    autoReload: false
    hasSearchField: true
    stateId: 284c8cb0-9b99-11ef-b1fd-f7b945601cd3
    sorters:
      - dir: asc
        prop: name
    store:
      proxy:
        service: Compose
        get:
          method: getConfigList
    columns:
      - name: "uuid"
        prop: uuid
        flexGrow: 1
        sortable: true
        hidden: true
      - name: _("Name")
        prop: name
        flexGrow: 1
        sortable: true
      - name: _("Description")
        prop: description
        flexGrow: 1
        sortable: true
      - name: _("Compose File")
        prop: composefile
        flexGrow: 1
        sortable: true
    actions:
      - type: menu
        icon: add
        tooltip: _("Add")
        actions:
          - text: _("Add")
            icon: add
            execute:
              type: url
              url: "/services/compose/configs/create"
          - text: _("Import")
            icon: mdi:file-import-outline
            execute:
              type: formDialog
              formDialog:
                title: _("Import config files from folders ...")
                fields:
                  - type: hint
                    hintType: info
                    text: _("This will import config files in from the selected folder.<br/>It will not import any config files that already exist in the plugin.")
                  - type: hidden
                    name: rootfsref
                    value: "79684322-3eac-11ea-a974-63a080abab18"
                    submitValue: false
                  - type: folderBrowser
                    name: path
                    label: _("Path")
                    value: ""
                    dirType: mntent
                    dirRefIdField: rootfsref
                  - type: select
                    name: fileref
                    label: _('Compose File')
                    textField: name
                    valueField: uuid
                    store:
                      proxy:
                        service: Compose
                        get:
                          method: enumerateFiles
                    hint: _("Compose file to be associate imported files with")
                buttons:
                  submit:
                    text: _("Import")
                    execute:
                      type: request
                      request:
                        service: Compose
                        method: importConfig
      - template: edit
        execute:
          type: url
          url: "/services/compose/configs/edit/{{ _selected[0].uuid }}"
      - template: delete
        execute:
          type: request
          request:
            service: Compose
            method: deleteConfig
            params:
              uuid: "{{ _selected[0].uuid }}"
      - type: iconButton
        icon: mdi:vector-difference
        tooltip: _("Show config changes")
        execute:
          type: taskDialog
          taskDialog:
            config:
              title: _("Show all file changes ...")
              startOnInit: true
              autoScroll: false
              request:
                service: Compose
                method: doGit
                params:
                  uuid: "{{ _selected[0].uuid }}"
                  command: "diffc"
        enabledConstraints:
          minSelected: 1
          maxSelected: 1
