version: "1.0"
type: component
data:
  name: omv-services-compose-file-form-page
  type: formPage
  config:
    request:
      service: Compose
      get:
        method: getFile
        params:
          uuid: "{{ _routeParams.uuid }}"
      post:
        method: setFile
    fields:
      - type: confObjUuid
      - type: textInput
        name: name
        label: _("Name")
        value: ""
        disabled: '{{ _routeConfig.data.editing | toboolean }}'
        validators:
          required: true
      - type: textInput
        name: description
        label: _("Description")
        value: ""
      - type: codeEditor
        name: body
        label: _("File")
        value: ""
        language: "yaml"
      - type: checkbox
        name: showenv
        label: _("Show environment file")
        value: false
      - type: codeEditor
        name: env
        label: _("Environment")
        value: ""
        language: "shell"
        modifiers:
          - type: visible
            constraint:
              operator: truthy
              arg0:
                prop: showenv
      - type: checkbox
        name: showoverride
        label: _("Show override")
        value: false
      - type: codeEditor
        name: override
        label: _("Override")
        value: ""
        language: "yaml"
        modifiers:
          - type: visible
            constraint:
              operator: truthy
              arg0:
                prop: showoverride
    buttons:
      - template: submit
        execute:
          type: url
          url: "/services/compose/files"
      - template: cancel
        execute:
          type: url
          url: "/services/compose/files"
